# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI for Frontend (Yarn) + Backend (Node.js)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install frontend dependencies
      working-directory: frontend
      run: yarn install

    - name: Build frontend
      working-directory: frontend
      run: yarn build

    - name: Install backend dependencies
      working-directory: backend
      run: npm install

    - name: Start backend (optional)
      working-directory: backend
      run: node server.js &
      
    - name: Run backend tests (optional)
      working-directory: backend
      run: npm test

