name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Library-Management-System-MERN/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: Library-Management-System-MERN/frontend/yarn.lock

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run frontend build
        run: yarn build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: Run tests (optional)
        run: yarn test
        continue-on-error: true
