name: CI for Frontend (Yarn)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock

    - name: Install dependencies (Yarn)
      working-directory: frontend
      run: yarn install

    - name: Build project
      working-directory: frontend
      run: yarn build

    - name: Run tests (if any)
      working-directory: frontend
      run: yarn test
