# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug folder structure
        run: |
          echo "Listing root directory:"
          ls -la
          echo "Listing frontend directory:"
          ls -la frontend || echo "Frontend folder not found!"

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: |
            frontend/yarn.lock

      - name: Install dependencies with Yarn
        working-directory: frontend
        run: yarn install

      - name: Build frontend
        working-directory: frontend
        run: yarn build

      - name: Run frontend tests (if available)
        working-directory: frontend
        run: |
          if yarn run | grep -q "test"; then
            yarn test
          else
            echo "No test script found in package.json"
          fi
